### ISSUE TITLE
Window missing side bar, bottom bar

### ISSUE THREAD

**Issue by ericvaladas** [codebasesaga/gitx#2]
This fork looks great! However, I just installed the latest release ([1.0.3](https://github.com/codebasesaga/gitx/releases/tag/1.0.3)) and it appears my window is missing some elements compared to the screen shot in the readme. I'm not sure if I'm missing something, but I don't see any options in the menu bar to show the side bar or bottom bar.

![screen shot](https://user-images.githubusercontent.com/828125/46578405-697bcd80-c9cd-11e8-86bf-960ef49b9c5f.png)

**Comment by mxcl** [comment]
Yeah, I have modified it since I took the screenshot.

I never use the bottom bar, so I have minimized the UI.

If you want the bottom bar, then I suggest forking it, you can undo the commits where I removed this stuff.

Or port my changes upstream, the maintainer there was not enthused with my alterations, hence this fork.

**Comment by ericvaladas** [comment]
I actually don't use those features either, so no big deal for me. I just wasn't sure if there was an issue. Thanks for the quick reply!

**Comment by mxcl** [comment]
I have updated the screenshot, thanks for bringing this to my attention.
